name: Run Docker Image on File Change

on:
  push:
    paths:
      - score-*.yaml

jobs:
  deploy-with-humctl:
    runs-on: ubuntu-latest
    env:
      HUMANITEC_APP: 5min-idp-eost

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Changed File and Set Environment
        id: determine-env
        run: |
          FILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'score-.*.yaml')
          echo "File changed: $FILE_CHANGED"
          if [[ "$FILE_CHANGED" == "score-dev.yaml" ]]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "SCORE_FILE=score-dev.yaml" >> $GITHUB_ENV
          elif [[ "$FILE_CHANGED" == "score-prod.yaml" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "SCORE_FILE=score-prod.yaml" >> $GITHUB_ENV
          else
            echo "No matching score file found."
            exit 1
          fi

      - name: Install Humctl
        run: |
          curl -sSL https://get.humanitec.io/cli | bash
          echo "$HOME/.humanitec/bin" >> $GITHUB_PATH

      - name: Call Humanitec
        env:
          HUMANITEC_API_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
        run: |
          humctl score deploy --app "$HUMANITEC_APP" --env $ENVIRONMENT -f ./$SCORE_FILE --wait
