name: Run Docker Image on File Change

on:
  push:
    paths:
      - score-*.yaml

jobs:
  deploy-with-humctl:
    runs-on: ubuntu-latest
    env:
      HUMANITEC_APP: 5min-idp-gxdm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Changed File and Set Environment
        id: determine-env
        run: |
          FILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'score-.*.yaml')
          echo "File changed: $FILE_CHANGED"
          if [[ "$FILE_CHANGED" == "score-dev.yaml" ]]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "SCORE_FILE=score-dev.yaml" >> $GITHUB_ENV
          elif [[ "$FILE_CHANGED" == "score-prod.yaml" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "SCORE_FILE=score-prod.yaml" >> $GITHUB_ENV
          else
            echo "No matching score file found."
            exit 1
          fi

      - name: Install Humctl
        run: |
          HUMCTL_URL=$(curl -s https://api.github.com/repos/Humanitec/cli/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d '"' -f 4)
          curl -fLO $HUMCTL_URL
          tar -zxvf *linux_amd64.tar.gz
          rm *linux_amd64.tar.gz README.md
          chmod +x humctl
          sudo mv humctl /usr/local/bin/
        shell: bash

      - name: Call Humanitec
        env:
          HUMANITEC_ORG: ${{ secrets.HUMANITEC_ORG }}
          HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
        run: |
          humctl score deploy --app "$HUMANITEC_APP" --env $ENVIRONMENT -f ./$SCORE_FILE --wait
        shell: bash
